easy_admin:
    site_name: '<img src="../img/logo.png" alt="Logo ALF"/><em style="font-size: 60%;">Services Publics</em> '
    list:
        max_results: 50

    formats:
        date:     'd/m/y'
        time:     'H:i'
        datetime: 'd/m/y H:i'

    entities:
        Utilisateur:
            class: App\Entity\User
        Gendarme:
             class: App\Entity\Gendarme
        Unit:
            class: App\Entity\Unit
        Grade:
            class: App\Entity\Grade
        Criminel:
            class: App\Entity\Criminel
        PV:
            class: App\Entity\PV
        TAJ:
            class: App\Entity\TAJ
        Magistrat:
            class: App\Entity\Magistrat
        Gardien:
            class: App\Entity\Gardien
        FVV:
            class: App\Entity\Vehicule
        COG:
            class: App\Entity\AppelCOG
        Post:
            class: App\Entity\Post
        Section:
            class: App\Entity\Section
        Prison:
            class: App\Entity\Prison
        Lieu:
            class: App\Entity\Lieu

    design:
        menu:
            - { label: 'Accueil', route: 'homepage', icon: 'home' }
            - { entity: 'Utilisateur', icon: 'users', label: 'Utilisateurs' }
            - label: 'Gendarmerie'
              children:
                - { entity: 'Gendarme', icon: 'user-circle', label: 'Effectif' }
                - { entity: 'PV', icon: 'folder', label: 'PVs' }
                - { entity: 'COG', icon: 'window-restore', label: 'C.O.G.' }
                - { entity: 'FVV', icon: 'window-restore', label: 'F.V.V.' }
                - { entity: 'Lieu', icon: 'tag', label: 'Lieux' }
            - label: 'Tribunal'
              children:
                - { entity: 'Magistrat', icon: 'user-circle', label: 'Effectif' }
            - label: 'Prison'
              children:
                - { entity: 'Gardien', icon: 'user-circle', label: 'Effectif' }
            - label: 'T.A.J.'
              children:
                - { entity: 'Criminel', icon: 'ban', label: 'Fiches' }
                - { entity: 'TAJ', icon: 'window-restore', label: 'Entrées' }
                - { entity: 'Prison', icon: 'window-restore', label: 'Incarcérations' }
            - label: 'Autre'
              children:
                - { entity: 'Grade', icon: 'tags', label: 'Grades' }
                - { entity: 'Unit', icon: 'object-group', label: 'Unités' }
                - { entity: 'Section', icon: 'object-group', label: 'Sections' }
                - { entity: 'Post', icon: 'window-restore', label: 'Posts' }
            - label: 'Env: %env(APP_ENV)%'